export interface IUserNotif {
    clerk_Id: string,
    subscribedOnRecomendedVideo: boolean,
    subscribedOnMySubscriptionChannelActivity: boolean,
    subscribedOnActivityOnMyChannel: boolean,
    subscribedOnOnActivityOnMyComments: boolean,
    subscribedOnOthersMentionOnMyChannel: boolean,
    subscribedOnShareMyContent: boolean,
    subscribedOnPromotionalContent: boolean,
    emailSubscribedOnMySubscriptionChannelActivity: boolean,
    emailSubscribedOnActivityOnMyChannel:boolean,
    emailSubscribedOnRecomendedVideo: boolean,
    emailSubscribedOnOnActivityOnMyComments: boolean,
    emailSubscribedOnOthersMentionOnMyChannel: boolean,
    emailSubscribedOnShareMyContent: boolean,
    emailSubscribedOnPromotionalContent: boolean,
    subscribedOnMainEmailNotifications: boolean,
}
